### ISSUE TITLE
fejl 

### ISSUE THREAD

**Issue by hedevej41** [MTrab/forsyning#10]
Når jeg prøver at tilføje forsynings integrationen efter den er installeret via hacs får jeg følgende fejl.

Config flow could not be loaded: {"message":"Invalid handler specified"}

og log siger 

Logger: homeassistant.config_entries
Source: config_entries.py:809
First occurred: 16:00:10 (4 occurrences)
Last logged: 16:00:34

Error occurred loading configuration flow for integration forsyning: cannot import name 'CURRENCY_LIST' from 'custom_components.forsyning.const' (/config/custom_components/forsyning/const.py)

**Comment by MTrab** [comment]
Øh ja?! Den er slet ikke frigivet til HACS og slet ikke klar.

Så nej, det virker ikke.

**Comment by MTrab** [comment]
Actually just released an early beta version right now. You could test that and see if it works as I only have access to their test environment.

**Comment by hedevej41** [comment]
nu kan jeg hive den frem i integrationer i ha men ser ud til kun at virke for aalborg forsyning. Jeg havde håbet lidt at den kunne hente data fra eforsyning.dk

**Comment by MTrab** [comment]
Desværre ikke, endnu.
